### PR TITLE
add ToJson implementation for Value.

### PR DESCRIPTION
**Pull request by miketang84**
Signed-off-by: Mike Tang miketang84@outlook.com

### CODE REVIEW

**Comment by SkylerLipthay** [comment]
Thank you for your pull request! params has just switched to depending on bodyparser 0.1, which in turn now relies on serde instead of rustc-serialize. As such, rustc-serialize is no longer used by params. We could certainly implement `serde::ser::Serialize` in a manner similar, though.

But I'm wondering, what problem is `impl ToJson for Value` solving? Currently, the responsibility of `params::Value` is only to act as a _deserialized_ collection of request parameters (as is made clear by the difficulty of implementing `ToJson` for `File`s). This crate has no interaction with `iron::response::Response`.

I would like to hear more about your situation! Please let me know if I can help.

**Comment by miketang84** [comment]
:), I need to get the request json params, and store it to pg's json type field, so I need ToJson. 

thx.

**Comment by daogangtang** [comment]
:), I need to get the request json params, and store it to pg's json type field, so I need ToJson. 

thx.

**Comment by SkylerLipthay** [comment]
I'm very sorry for the late response!

Ultimately I do not think that this specific behavior belongs in the crate. The re-serialization of request parameters may have a legitimate use case (like in your instance, for logging the parameters as a JSON value in your database), but I do not think `params` should make any assumptions about how exactly this should be done. Specifically, how should file parameters be handled? Here, you `panic!` on encountering a file, but perhaps some users would like to silently ignore the file, or convert it and log the file as a string of file metadata.

There's also an argument for the separation of concerns here. Again, as it stands, `params` exists only to handle deserialization.

For these reasons, I recommend you instead simply implement `ToJson` on a newtype struct wrapper around `params::Value`:

``` rust
use rustc_serialize::json::{self, Json, ToJson};
use params::Value;

struct JsonLoggableParamsValue(Value);

impl ToJson for JsonLoggableParamsValue {
    fn to_json(&self) -> Json {
        match self.0 {
            Value::Null => Json::Null,
            Value::Boolean(value) => value.to_json(),
            Value::I64(value) => value.to_json(),
            Value::U64(value) => value.to_json(),
            Value::F64(value) => value.to_json(),
            Value::String(ref value) => value.to_json(),
            //Value::File(ref value) => value.fmt(f),
            Value::Array(ref value) => {
                let result: json::Array = value.iter().map(|v| v.to_json()).collect();
                result.to_json()
            },
            Value::Map(ref value) => {
                let mut result: json::Object = json::Object::new();
                let Map(ref map) = *value;
                for (key, val) in map {
                    result.insert(key.clone(), val.to_json());
                }
                result.to_json()
            },
            _ => {
                panic!("Params containing File should not be jsonrized.");
            }
        }
    }
}
```

I apologize for the inconvenience!

**Pull request closed without merging**
