### PR TITLE
Updates for iron 0.6 and serde 1.0, bump version

### PR DESCRIPTION
**Pull request by robinst**
* Update serde to 1.0 (rebased #35)
* Remove maplit (seems to be unused now)
* Update iron deps, bump version

@untitaker this contains all the changes from #35 and #38. If you can merge and release this, that would be great! Then we can close the other PRs.

### CODE REVIEW

**Comment by kyegupov** [comment]
Can this be merged? This package is currently incompatible with iron 0.6 :(

**Comment by robinst** [comment]
@untitaker friendly ping

**Comment by SkylerLipthay** [comment]
I'm merging this now!

**Comment by SkylerLipthay** [comment]
`0.8.0` has been published. Sorry for the delay. Thanks @robinst for your diligence and patience :) I'll close up the other PRs.

**Pull request merged**
