### PR TITLE
update serde and bodyparser

### PR DESCRIPTION
**Pull request by euclio**
Serde 1.0! Yay!

### CODE REVIEW

**Comment by euclio** [comment]
Er, actually maybe don't merge this until iron/urlencoded#70 is merged and published, so I can update that too.

**Comment by ghost** [comment]
https://github.com/iron/urlencoded/pull/70
is merged already..

**Comment by euclio** [comment]
@xliiv It's merged but it hasn't been released. I haven't been able to contact a maintainer to make the version bump/publish. See iron/urlencoded#68.

**Comment by robinst** [comment]
FYI I've rolled this into another PR which also bumps the other iron crates now that they've been released: https://github.com/iron/params/pull/39

**Comment by SkylerLipthay** [comment]
Closed by #39, finally!

**Pull request closed without merging**
