### PR TITLE
Update dependencies to iron-0.5

### PR DESCRIPTION
**Pull request by onur**

### CODE REVIEW

**Comment by Hoverbear** [comment]
Thanks!

**Comment by sunng87** [comment]
Could you please create a release for this?

**Comment by Hoverbear** [comment]
@SkylerLipthay I don't have permissions to publish. I tagged and commited the new version. Can you publish?

**Comment by SkylerLipthay** [comment]
Hm.. you should have permissions as an Iron team member. But anyway, I published 0.6! Sorry for the delay.

**Comment by sunng87** [comment]
Thank you!

**Pull request merged**
